// <auto-generated />
using System;
using Group4_WebAppFinal.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group4_WebAppFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240422004430_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.Bag", b =>
                {
                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemName");

                    b.ToTable("Bags");

                    b.HasData(
                        new
                        {
                            ItemName = "Potion",
                            Description = "Restores 10HP",
                            ItemQuantity = 1,
                            ItemType = "Consumable"
                        });
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.Pokemon", b =>
                {
                    b.Property<int>("DexNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DexNumberID"));

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DexNumberID");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.PokemonType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PokemonDexNumberID")
                        .HasColumnType("int");

                    b.HasKey("TypeName");

                    b.HasIndex("PokemonDexNumberID");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            TypeName = "None"
                        },
                        new
                        {
                            TypeName = "Normal"
                        },
                        new
                        {
                            TypeName = "Fire"
                        },
                        new
                        {
                            TypeName = "Water"
                        },
                        new
                        {
                            TypeName = "Electric"
                        },
                        new
                        {
                            TypeName = "Grass"
                        },
                        new
                        {
                            TypeName = "Ice"
                        },
                        new
                        {
                            TypeName = "Fighting"
                        },
                        new
                        {
                            TypeName = "Poison"
                        },
                        new
                        {
                            TypeName = "Ground"
                        },
                        new
                        {
                            TypeName = "Flying"
                        },
                        new
                        {
                            TypeName = "Psychic"
                        },
                        new
                        {
                            TypeName = "Bug"
                        },
                        new
                        {
                            TypeName = "Rock"
                        },
                        new
                        {
                            TypeName = "Ghost"
                        },
                        new
                        {
                            TypeName = "Dragon"
                        },
                        new
                        {
                            TypeName = "Dark"
                        },
                        new
                        {
                            TypeName = "Steel"
                        },
                        new
                        {
                            TypeName = "Fairy"
                        });
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("BagItemName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PokemonDexNumberID")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("BagItemName");

                    b.HasIndex("PokemonDexNumberID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.PokemonType", b =>
                {
                    b.HasOne("Group4_WebAppFinal.Controllers.Entities.Pokemon", null)
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonDexNumberID");
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.Team", b =>
                {
                    b.HasOne("Group4_WebAppFinal.Controllers.Entities.Bag", "Bag")
                        .WithMany()
                        .HasForeignKey("BagItemName");

                    b.HasOne("Group4_WebAppFinal.Controllers.Entities.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonDexNumberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Group4_WebAppFinal.Controllers.Entities.Pokemon", b =>
                {
                    b.Navigation("PokemonTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
