@MinimalApiHost = https://localhost:7294

###
#return all pokemon records
GET {{MinimalApiHost}}/api/pokemon

###
GET {{MinimalApiHost}}/api/pokemon/

###
POST {{MinimalApiHost}}/api/pokemon
Content-Type: application/json

{
  "pokemonName": "Charmander",
  "DexNumberID": "500",
  "type1": "Rock",
  "type2": "Water"
}

