@MinimalApiHost = https://localhost:7294

###
#return all pokemon records
GET {{MinimalApiHost}}/api/pokemon

###
GET {{MinimalApiHost}}/api/pokemon/8

###
POST {{MinimalApiHost}}/api/pokemon/
Content-Type: application/json

{
  "PokemonName": "Ivysaur",
  "Type1": "Grass",
  "Type2": "N/A"
}

